parameters:
    uploads_directory: '%kernel.project_dir%/public/uploads'


services:
    # Configuration par défaut
    _defaults:
        autowire: true      # Injection automatique
        autoconfigure: true # Auto-enregistrement des commandes, events, etc.

    # Charger tous tes services dans src/
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Définir correctement BrevoMailerService
    App\Service\BrevoMailerService:
        arguments:
            $client: '@http_client'
